using Sudoku.Constraints;

namespace Sudoku.Common;

/// <summary>
/// A (line of) sums of 10 contains on or more contigous groups of cells, each
/// of which sums to 10. These groups of cells cannot overlap.
/// </summary>
/// <example>
/// ...│.6.│...
/// ...│.4.│...
/// ...│.2.│...
/// ───┼───┼───
/// ...│.1.│...
/// 163│25.│...
/// ...│...│...
/// ───┼───┼───
/// ...│...│...
/// ...│...│...
/// ...│...│...
/// </example>
public static partial class Lines
{
    [Pure]
    public static IEnumerable<SumsOfTen> SumsOfTen(string grid) => Parse(grid)
        .Select(line => new SumsOfTen([..line]));
}
