namespace Sudoku.Common;

/// <summary>
/// Renban lines contain a non-repeating set of consecutive digits in any order.
/// </summary>
/// <example>
/// ...│.8.│...
/// ...│.7.│...
/// ...│.5.│...
/// ───┼───┼───
/// ...│.64│...
/// ...│...│...
/// ...│...│...
/// ───┼───┼───
/// ...│...│...
/// ...│...│...
/// ...│...│...
/// </example>
public static class RenbanLines
{
    [Pure]
    public static IEnumerable<RenbanLine> Parse(string str)
        => NamedCage.Parse(str).Select(cage => new RenbanLine(cage.Cells));
}
