using Sudoku.Restrictions;

namespace Sudoku.Common;

/// <summary>
/// A (line of) sums of 10 contains on or more contigous groups of cells, each
/// of which sums to 10. These groups of cells cannot overlap.
/// </summary>
/// <example>
/// ...│.6.│...
/// ...│.4.│...
/// ...│.2.│...
/// ───┼───┼───
/// ...│.1.│...
/// 163│25.│...
/// ...│...│...
/// ───┼───┼───
/// ...│...│...
/// ...│...│...
/// ...│...│...
/// </example>
public static class SumsOfTens
{
    [Pure]
    public static IEnumerable<SumsOfTen> Parse(string str)
        => Lines.Parse(str)
        .SelectMany(line => Group.Select(line, (a, _) => new SumsOfTen(a, line)));

}
