namespace Puzzles.CrackingTheCryptic;

public sealed class _2024_12_24 : CtcPuzzle
{
    public override string Title => "Arrow Thermo 2";

    public override string? Author => "Aad van de Wetering";

    public override Uri? Url => new("https://youtu.be/2VFxX_4T4r0");

    public override O Duration => O.s;

    public override Clues Clues { get; } = Clues.Parse("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│1..│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ..7│..2│...
        """);

    public override Cells Solution { get; } = Cells.Parse("""
        358│726│941
        471│359│286
        692│841│357
        ───┼───┼───
        723│965│418
        846│173│529
        519│284│763
        ───┼───┼───
        235│698│174
        184│537│692
        967│412│835
        """);

    public override Rules Constraints { get; }
        = Rules.Standard
        + Thermometers.Parse("""
        A..│...│..a
        B.G│...│g.b
        C.H│.M.│h.c
        ───┼───┼───
        D.I│.N.│i.d
        E.J│.O.│j.e
        ..K│.P.│k..
        ───┼───┼───
        ...│.Q.│...
        ...│...│...
        ...│...│...
        """)
        + Arrows.ParseSets("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        A..│...│..a
        B.F│...│f.b
        ───┼───┼───
        C.G│.J.│g.c
        D.H│K..│h.d
        ...│L..│...
        """)
        + Arrows.ParseSets("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│.j.│...
        ...│..k│...
        ...│..l│...
        """);
}
