
namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_09_15 : CtcPuzzle
{
    public override string Title => "Studious";
    public override string? Author => "James Sinclair";
    public override Uri? Url => new("https://youtu.be/qEGLhzb_IZE");

    public override Clues Clues { get; } = Clues.None;

    public override Cells Solution { get; } = Cells.Parse("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        """);

    public override ImmutableArray<Constraint> Constraints { get; } =
    [
        .. Rules.Standard,
        .. RenbanLines.Parse("""
        ...|...|...
        ...|...|...
        ...|.AB|...
        ---+---+---
        ...|...|C..
        ...|...|DH.
        K..|..F|G..
        ---+---+---
        L..|...|...
        M..|...|...
        .NO|P..|...
        """),

        .. GermanWhispers.Parse("""
        ABC|...|HIJ
        FED|.M.|..K
        ...|N..|...
        ---+---+---
        ...|.O.|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|.cd
        ...|...|.be
        ...|...|.af
        """),

        Arrow.Parse("""
        ...|...|...
        ...|...|...
        321|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        """),
        Arrow.Parse("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|3..|...
        ...|21.|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        """),
        Arrow.Parse("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|.1.|...
        ---+---+---
        ..3|2..|...
        ...|...|...
        ...|...|...
        """),
        Arrow.Parse("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|3..
        ...|...|2..
        ...|...|1..
        """),
    ];
}
