namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_04 : CtcPuzzle
{
    public override string Title => "Lockdown";

    public override string? Author => "Dorlir";

    public override Uri? Url => new("https://youtu.be/NsiGrBiISOs");

    public override O Duration => O.s;

    public override Clues Clues { get; } = Clues.Parse("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│.5.
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│.3.│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.Parse("""
        814│957│362
        697│423│815
        352│186│974
        ───┼───┼───
        936│548│721
        128│679│453
        745│312│689
        ───┼───┼───
        579│264│138
        481│735│296
        263│891│547
        """);

    public override Rules Constraints { get; }
        = Rules.Standard
        + GermanWhispers.Parse("""
        .B.│...│...
        A..│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│..c│d..
        ...│.b.│...
        ───┼───┼───
        ...│.a.│...
        ...│...│...
        ...│...│...
        """)
        + Twins.Parse("""
        .AB│...│...
        C..│B..│...
        D..│A..│...
        ───┼───┼───
        .DC│...│...
        ...│...│...
        ...│...│EF.
        ───┼───┼───
        ...│..G│..F
        ...│..H│..E
        ...│...│HG.
        """)
        + SameSum.Parse("""
        ...│...│...
        ...│.C.│...
        ...│.C.│...
        ───┼───┼───
        ...│.B.│...
        .AA│B..│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + SameSum.Parse("""
        ...│...│AA.
        ...│..B│..E
        ...│..B│C.E
        ───┼───┼───
        ...│...│DD.
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + SameSum.Parse("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        .BB│...│...
        ───┼───┼───
        A.C│D..│...
        A..│D..│...
        .EE│...│...
        """);
}
