namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_20 : CtcPuzzle
{
    public override string Title => "Zebra Knights";

    public override string? Author => "R.Mullinix";

    public override Uri? Url => new("https://youtu.be/8zHIxRFOX9c");

    public override O Duration => O.μs100;

    public override Clues Clues { get; } = Clues.Parse("""
        ...│...│..4
        8..│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.Parse("""
        675│189│324
        891│423│675
        234│675│891
        ───┼───┼───
        123│798│546
        987│546│132
        546│231│789
        ───┼───┼───
        362│917│458
        719│854│263
        458│362│917
        """);

    public override Rules Constraints { get; }
        = Rules.AntiKnight
        + WhiteDots.Parse("""
        ...│...│...
        ...│...│...
        ...│AA.│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│.BB│...
        ...│...│...
        """)
       + RenbanLines.Parse("""
        ...│...│...
        ..A│...│...
        AA.│...│...
        ───┼───┼───
        ...│...│...
        ...│BBB│...
        ...│...│CCC
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Thermometers.Parse("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ABC│.E.│.JK
        .HG│D..│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Jigsaw.Parse("""
        ...│...│...
        ..A│...│...
        AA.│...│...
        ───┼───┼───
        ...│...│...
        ...│AAA│...
        ..C│CC.│AAA
        ───┼───┼───
        ...│...│...
        ...│CCC│...
        ...│...│CCC
        """)
        + Jigsaw.Parse("""
        ...│...│...
        ...│...│...
        ...│AA.│...
        ───┼───┼───
        BBB│.B.│.BB
        .BB│B..│...
        ...│...│.AA
        ───┼───┼───
        ...│...│...
        ...│.AA│...
        ...│...│...
        """);
}
