
namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_09_15 : CtcPuzzle
{
    public override string Title => "Studious";
    public override string? Author => "James Sinclair";
    public override Uri? Url => new("https://youtu.be/qEGLhzb_IZE");
    public override O Duration => O.s10;

    public override Cells Solution { get; } = Cells.Parse("""
        728|645|391
        493|182|756
        516|379|284
        ---+---+---
        142|897|635
        369|451|827
        875|263|149
        ---+---+---
        981|536|472
        637|924|518
        254|718|963
        """);

    public override Rules Constraints { get; } =
        Rules.Standard
        + RenbanLines.Parse("""
        ...|...|...
        ...|...|...
        ...|.AA|...
        ---+---+---
        ...|...|A..
        ...|...|AC.
        B..|..C|C..
        ---+---+---
        B..|...|...
        B..|...|...
        .BB|B..|...
        """)
        + GermanWhispers.Parse("""
        ABC|...|HIJ
        FED|.M.|..K
        ...|N..|...
        ---+---+---
        ...|.O.|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|.cd
        ...|...|.be
        ...|...|.af
        """)
        + Arrow.ParseSet("""
        ...|...|...
        ...|...|...
        321|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        """)
        + Arrow.ParseSet("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|3..|...
        ...|21.|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        """)
        + Arrow.ParseSet("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|.1.|...
        ---+---+---
        ..3|2..|...
        ...|...|...
        ...|...|...
        """)
        + Arrow.ParseSet("""
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|...
        ...|...|...
        ...|...|...
        ---+---+---
        ...|...|3..
        ...|...|2..
        ...|...|1..
        """);
}
