<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <EmbeddedResource Include="Restrictions/*.md" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <PackageReference PrivateAssets="all" Include="Qowaiv.Analyzers.CSharp" />
    <PackageReference PrivateAssets="all" Include="StyleCop.Analyzers.Unstable" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Update="DotNetProjectFile.Analyzers" Version="1.7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNetProjectFile.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
