global using Sudoku;
global using Sudoku.Contracts;
global using Sudoku.Diagnostics;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Text;
global using static Sudoku.Statics;
