namespace Puzzles.CrackingTheCryptic;

public sealed class _2020_04_22 : CtcPuzzle
{
    public override string Title => "CTC";

    public override string? Author => "Ashish Kumar";

    public override Uri? Url => new("https://youtu.be/kgpFXlBftIQ");

    public override O Duration => O.μs10;

    public override Clues Clues { get; } = Clues.New("""
        ...│...│9..
        ...│...│.6.
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        .4.│..6│...
        ..5│...│...
        """);

    public override Cells Solution { get; } = Cells.New("""
        321│658│947
        457│139│862
        698│724│135
        ───┼───┼───
        789│261│354
        214│583│796
        563│497│218
        ───┼───┼───
        836│975│421
        942│816│573
        175│342│689
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.AntiKnight
        + Lines.Thermometer("""
        CBA│...│...
        D..│...│...
        E..│.JK│...
        ───┼───┼───
        FGH│...│...
        ...│...│...
        ...│...│.MN
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Lines.Thermometer("""
        ...│...│...
        ...│...│...
        ...│BA.│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│ED.
        ───┼───┼───
        ...│...│F..
        ...│...│G..
        ...│...│HIJ
        """)
        + Lines.Thermometer("""
        ...│...│...
        ...│...│...
        ...│.A.│...
        ───┼───┼───
        ...│.B.│...
        ...│.C.│...
        ...│.D.│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        ;
}
