using DynamicSolver;
using Sudoku.Common;
using Sudoku.Validation;

namespace Specs.Common.SumOfTen_specs;

public class Restricts
{
    [TestCase(0, 6)]
    [TestCase(1, 4)]
    [TestCase(2, 2)]
    [TestCase(3, 1)]
    [TestCase(4, 5)]
    [TestCase(5, 1, 2)]
    [TestCase(6, 3)]
    [TestCase(7, 6)]
    [TestCase(8, 1)]
    public void Involved_cells(int index, params int[] digits)
    {
        Digits allowed = [..digits];

        var cells = Links.New(Clues.Parse("""
            ...│.6.│...
            ...│.4.│...
            ...│.2.│...
            ───┼───┼───
            ...│.1.│...
            .63│.5.│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            ...│...│...
            """), Rules.Basic);
        
        var rest = SumsOfTens.Parse("""
            ...|.A.|...
            ...|.B.|...
            ...|.C.|...
            ---+---+---
            ...|.D.|...
            IHG|FE.|...
            ...|...|...
            ---+---+---
            ...|...|...
            ...|...|...
            ...|...|...
            """).ToArray();

        var res = rest[index];
        res.Restrict(cells).Should().Be(allowed);
    }
}
