global using Sudoku;
global using Sudoku.Common;
global using Sudoku.Contracts;
global using Sudoku.Parsing;
global using Sudoku.Restrictions;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using static Sudoku.Statics;
global using LookupDigits = Sudoku.Generics.DigitLookup<Sudoku.Digits>;
