namespace Puzzles.CrackingTheCryptic;

public sealed class _2026_06_07 : CtcPuzzle
{
    public override string Title => "Titled Squares";

    public override string? Author => "Simply Spicy";

    public override Uri? Url => new("https://youtu.be/wDJAhLRxVSo");

    public override O Duration => O.μs100;

    public override Cells Solution { get; } = Cells.New("""
        564│927│183
        321│568│497
        798│341│562
        ───┼───┼───
        635│492│871
        842│175│639
        179│836│245
        ───┼───┼───
        916│754│328
        283│619│754
        457│283│916
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Killer("""
        ...│...│...
        AE.│...│...
        AE.│...│...
        ───┼───┼───
        ...│...│.C.
        ...│...│.C.
        ...│...│...
        ───┼───┼───
        BBB│...│...
        BBB│.DD│...
        ...│...│...
        E=11 B=29 A=C=D=10
        """)
        + Lines.GermanWhisper("""
        ..A│BCD│EFG
        ...│.I.│...
        ...│..J│...
        ───┼───┼───
        ...│...│K..
        .N.│...│.L.
        ..O│...│...
        ───┼───┼───
        ...│Q..│...
        ...│.R.│...
        ..a│bcd│efg
        """)
        + Lines.Renban("""
        ...│...│...
        ...│.A.│...
        ...│A..│...
        ───┼───┼───
        ..A│...│...
        .A.│...│.B.
        ...│...│B..
        ───┼───┼───
        ...│..B│...
        ...│.B.│...
        ...│...│...
        """)
        + Lines.SameParity("""
        ...│...│...
        ...│...│A..
        ...│...│.AA
        ───┼───┼───
        ...│.B.│...
        ...│B.B│...
        ...│.B.│...
        ───┼───┼───
        CC.│...│...
        ..C│...│...
        ...│...│...
        """)
        + Couples.BlackDots("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│..B
        ..A│A..│..B
        ...│...│...
        """)
        + Couples.WhiteDots("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        AA.│...│...
        """)
        + KillerCages.Extend
       ;
}
