namespace Puzzles.CrackingTheCryptic;

public sealed class _2026_03_13 : CtcPuzzle
{
    public override string Title => "Dancing In A Ring";

    public override string? Author => "Fool On Hill";

    public override Uri? Url => new("https://youtu.be/I-2gLlYheHs");

    public override O Duration => O.ms10;

    public override Cells Solution { get; } = Cells.New("""
        974│851│632
        863│927│541
        251│634│987
        ───┼───┼───
        736│189│425
        489│562│713
        512│743│869
        ───┼───┼───
        697│218│354
        148│395│276
        325│476│198
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.Renban("""
        AA.│...│.BB
        AA.│...│.BB
        ...│.X.│...
        ───┼───┼───
        ...│.X.│...
        ..X│XXX│X..
        ...│.X.│...
        ───┼───┼───
        ...│.X.│...
        CC.│...│.DD
        CC.│...│.DD
        """)
        + Lines.GermanWhisper("""
        ...│...│...
        ...│...│...
        ..A│B.a│b..
        ───┼───┼───
        ..D│C.d│c..
        ...│...│...
        ..K│L.k│l..
        ───┼───┼───
        ..N│M.n│m..
        ...│...│...
        ...│...│...
        """)
        + Lines.GermanWhisper("""
        ...│...│...
        ...│...│...
        ..A│..a│...
        ───┼───┼───
        ..B│..b│...
        ...│...│...
        ..O│..o│...
        ───┼───┼───
        ..P│..p│...
        ...│...│...
        ...│...│...
        """)
        + Couples.WhiteDots("""
        ...│...│...
        ...│.A.│BB.
        ...│.A.│...
        ───┼───┼───
        ...│...│...
        .CC│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│.DD│...
        """)
        + Couples.BlackDots("""
        ..A│A..│...
        ...│...│.B.
        ...│...│.B.
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        .CC│...│...
        ...│...│...
        """)
        + Couples.Ratio1_2((7, 1), (8, 1));
}
