namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_09_25 : CtcPuzzle
{
    public override string Title => "Threads Of Silence";

    public override string? Author => "Dorlir";

    public override Uri? Url => new("https://youtu.be/acFMVXxSN5A");

    public override O Duration => O.s;

    public override Clues Clues { get; } = Clues.Parse("""
        8..│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.Parse("""
        845│639│271
        739│421│658
        162│758│493
        ───┼───┼───
        258│316│749
        913│247│865
        476│985│312
        ───┼───┼───
        587│162│934
        391│874│526
        624│593│187
        """);

    public override Rules Constraints { get; }
        = Rules.Standard
        + Yellow()
        + ZipLines.Parse("""
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            ...│..E│FGH
            ───┼───┼───
            ...│..D│..I
            ...│..C│...
            ...│..B│A..
            """)
        + RenbanLines.Parse("""
        ...│R..│...
        ...│R..│...
        ...│R..│...
        ───┼───┼───
        RRR│R..│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + SumsOfTens.Parse("""
        ...│.A.│...
        ...│.B.│...
        ...│.C.│...
        ───┼───┼───
        ...│.D.│...
        IHG│FE.│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + GermanWhispers.Parse("""
        ...│..C│DEF
        ...│..B│A.G
        ...│...│.KH
        ───┼───┼───
        ...│...│.JI
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """);

    private static IEnumerable<Restriction> Yellow()
    {
        var line = Lines.Parse("""
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            CBA│...│...
            ───┼───┼───
            D..│K..│...
            E..│J..│...
            FGH│I..│...
            """).Single();

        for (var f = 0; f < line.Length - 1; f++)
        {
            for (var s = f + 1; s < line.Length; s++)
            {
                var dis = s - f;
                var pairs = new LookupPair(line[f], line[s], dis % 5 is 0 ? Same : Diff).Couple();
                yield return pairs.One;
                yield return pairs.Two;
            }
        }
    }

    private static readonly LookupDigits Same = LookupPair.SameClass([[1, 6], [2, 7], [3, 8], [4, 9], [5]]);
    private static readonly LookupDigits Diff = LookupPair.DiffClass([[1, 6], [2, 7], [3, 8], [4, 9], [5]]);
}
