namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_04 : CtcPuzzle
{
    public override string Title => "Lockdown";

    public override string? Author => "Dorlir";

    public override Uri? Url => new("https://youtu.be/NsiGrBiISOs");

    public override O Duration => O.s;

    public override Clues Clues { get; } = Clues.New("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│.5.
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│.3.│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.New("""
        814│957│362
        697│423│815
        352│186│974
        ───┼───┼───
        936│548│721
        128│679│453
        745│312│689
        ───┼───┼───
        579│264│138
        481│735│296
        263│891│547
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.GermanWhisper("""
        .B.│...│...
        A..│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│..c│d..
        ...│.b.│...
        ───┼───┼───
        ...│.a.│...
        ...│...│...
        ...│...│...
        """)
        + Couples.Twins("""
        .AB│...│...
        C..│B..│...
        D..│A..│...
        ───┼───┼───
        .DC│...│...
        ...│...│...
        ...│...│EF.
        ───┼───┼───
        ...│..G│..F
        ...│..H│..E
        ...│...│HG.
        """)
        + Groups.Cages("""
        ...│...│aa.
        ...│.Xb│..e
        ...│.Xb│c.e
        ───┼───┼───
        ...│.Y.│dd.
        .ZZ│Y..│...
        .BB│...│...
        ───┼───┼───
        A.C│D..│...
        A..│D..│...
        .EE│...│...

        X=Y=Z A=B=C=D=E a=b=c=d=e
        """);
}
