namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_01_31 : CtcPuzzle
{
    public override string Title => "ZL GW DA";

    public override string? Author => "ICHTUES";

    public override Uri? Url => new("https://youtu.be/FF9Bc77uh5I");

    public override O Duration => O.ms100;

    public override Cells Solution { get; } = Cells.New("""
        954│132│678
        283│576│491
        176│984│352
        ───┼───┼───
        597│421│836
        468│793│125
        321│865│947
        ───┼───┼───
        739│218│564
        842│659│713
        615│347│289
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.GermanWhisper("""
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ...│A.C│...
            ...│.B.│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            ...│...│...
            """)
         + Lines.GermanWhisper("""
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ...│.A.│...
            ...│.BC│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            ...│...│...
            """)
        + Lines.DoubleArrow("""
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ...│...│...
            ...│...│...
            ...│...│...
            ───┼───┼───
            ABC│DEF│...
            abc│def│...
            HIJ│KLM│...
            """)
        + Lines.Zip("""
            .AB|CDE|FGH
            .ab|cde|fgI
            ...|...|.hJ
            ---+---+---
            ...|...|.iK
            ...|...|.jL
            ...|...|.kM
            ---+---+---
            x..|...|.lN
            y..|...|.mO
            .z.|...|...
            """);
}
