namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_22 : CtcPuzzle
{
    public override string Title => "Arrow Renban Sudoku";

    public override string? Author => "Christounet";

    public override Uri? Url => new("https://youtu.be/zA4PshGRoVk");

    public override O Duration => O.ms10;

    public override Cells Solution { get; } = Cells.New("""
        321│867│549
        798│534│261
        546│129│738
        ───┼───┼───
        914│786│352
        653│492│187
        872│315│694
        ───┼───┼───
        267│958│413
        185│243│976
        439│671│825
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.Renban("""
        ...│AAA│...
        ...│BBB│...
        ..B│...│B..
        ───┼───┼───
        ...│CCC│...
        DD.│...│.EE
        FD.│...│.E.
        ───┼───┼───
        .FF│.G.│...
        ..F│.G.│...
        ...│...│...
        """)
        + Lines.Arrow("""
        Aaa│...│bbB
        ...│...│...
        C..│...│..D
        ───┼───┼───
        .cc│...│dd.
        ..e│Ed.│...
        ..e│.f.│..g
        ───┼───┼───
        ...│F.F│gG.
        ...│...│g..
        ...│...│...
        """)
        + Lines.Arrow("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│.Aa│a..
        ...│...│a..
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Couples.BlackDots("""
        ...│.A.│...
        ...│.A.│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """);
}
