namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_24 : CtcPuzzle
{
    public override string Title => "Star Of Bethlehem";

    public override string? Author => "Aspartageus";

    public override Uri? Url => new("https://youtu.be/YqFiRxhodQA");

    public override O Duration => O.ms;

    public override Cells Solution { get; } = Cells.New("""
        742│986│135
        568│123│974
        193│745│682
        ───┼───┼───
        435│619│728
        817│254│369
        926│837│451
        ───┼───┼───
        384│571│296
        279│468│513
        651│392│847
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.DutchWhispers("""
        ..a│...│A..
        .b.│...│.B.
        c..│...│..C
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        e..│...│..E
        .f.│...│.F.
        ..g│...│G..
        """)
       + Lines.Renban("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│.A.│...
        ...│AAA│...
        ...│.A.│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Lines.Arrow("""
        ...│.A.│...
        ...│..B│...
        ...│..C│...
        ───┼───┼───
        .FG│...│...
        E..│...│..e
        ...│...│gf.
        ───┼───┼───
        ...│c..│...
        ...│b..│...
        ...│.a.│...
        """)
        + Lines.Arrow("""
        ...│.A.│...
        ...│B..│...
        ...│C..│...
        ───┼───┼───
        ...│...│gf.
        E..│...│..e
        .FG│...│...
        ───┼───┼───
        ...│..c│...
        ...│..b│...
        ...│.a.│...
        """)
        + Lines.Arrow("""
        ...│...│...
        ...│.C.│...
        ...│.B.│...
        ───┼───┼───
        ...│A.e│...
        .GF│...│fg.
        ...│E.a│...
        ───┼───┼───
        ...│..b│...
        ...│.c.│...
        ...│...│...
        """)
       + Lines.Arrow("""
        ...│...│...
        ...│..G│...
        ..B│...│F..
        ───┼───┼───
        .C.│A.E│...
        ...│...│...
        ...│e.a│.c.
        ───┼───┼───
        ..f│...│b..
        ...│g..│...
        ...│...│...
        """);
}
