namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_03_25 : CtcPuzzle
{
    public override string Title => "Rapuzzle";

    public override string? Author => "Scojo";

    public override Uri? Url => new("https://youtu.be/-L9qq8cyQ5M");

    public override O Duration => O.μs100;

    public override Clues Clues { get; } = Clues.New("""
        ...│.2.│...
        ...│...│...
        ...│...│...
        ---┼---┼---
        ...│...│...
        ...│...│...
        ...│...│...
        ---┼---┼---
        ...│...│...
        ...│...│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.New("""
        471│928│536
        836│571│924
        925│436│187
        ───┼───┼───
        194│382│675
        387│695│241
        652│147│398
        ───┼───┼───
        549│813│762
        218│769│453
        763│254│819
        """);

    protected override RuleSet GetConstraints() =>
        RuleSet.AntiKnight
        + Tower()
        + Lines.Entropic("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        .AB│C..│...
        ..D│E..│...
        ..F│...│...
        ───┼───┼───
        ...│G.I│...
        ...│.HJ│K..
        ...│...│.L.
        """);

    private static Rules Tower()
    {
        var tower = Grid.NamedGroups("""
            .T.│...│...
            TTT│...│...
            TTT│...│...
            ───┼───┼───
            TTT│...│...
            TTT│...│...
            TTT│...│...
            ───┼───┼───
            TTT│...│...
            TTT│...│...
            TTT│...│...
            """).Single();

        return tower.Cells.SelectMany(Tower);

        Rules Tower(Pos t) =>
        [
            .. t.N() is { } n && !tower.Cells.Contains(n) ? n.LT(t) : [],
            .. t.W() is { } w && !tower.Cells.Contains(w) ? w.LT(t) : [],
            .. t.E() is { } e && !tower.Cells.Contains(e) ? e.LT(t) : [],
        ];
    }
}
