namespace Puzzles.CrackingTheCryptic;

public sealed class _2025_12_24 : CtcPuzzle
{
    public override string Title => "Star Of Bethlehem";

    public override string? Author => "Aspartageus";

    public override Uri? Url => new("https://youtu.be/YqFiRxhodQA");

    public override O Duration => O.ms;

    public override Cells Solution { get; } = Cells.New("""
        742│986│135
        568│123│974
        193│745│682
        ───┼───┼───
        435│619│728
        817│254│369
        926│837│451
        ───┼───┼───
        384│571│296
        279│468│513
        651│392│847
        """);

    protected override RuleSet GetConstraints()
        => RuleSet.Standard
        + Lines.DutchWhisper("""
        ..a│...│A..
        .b.│...│.B.
        c..│...│..C
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        e..│...│..E
        .f.│...│.F.
        ..g│...│G..
        """)
       + Lines.Renban("""
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│.A.│...
        ...│AAA│...
        ...│.A.│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """)
        + Lines.Arrow("""
        ...│.A.│...
        ...│..a│...
        ...│..a│...
        ───┼───┼───
        .cc│...│...
        C..│...│..D
        ...│...│dd.
        ───┼───┼───
        ...│b..│...
        ...│b..│...
        ...│.B.│...
        """)
        + Lines.Arrow("""
        ...│.A.│...
        ...│a..│...
        ...│a..│...
        ───┼───┼───
        ...│...│dd.
        C..│...│..D
        .cc│...│...
        ───┼───┼───
        ...│..b│...
        ...│..b│...
        ...│.B.│...
        """)
        + Lines.Arrow("""
        ...│...│...
        ...│.a.│...
        ...│.a.│...
        ───┼───┼───
        ...│A.D│...
        .cc│...│dd.
        ...│C.B│...
        ───┼───┼───
        ...│..b│...
        ...│.b.│...
        ...│...│...
        """)
       + Lines.Arrow("""
        ...│...│...
        ...│..d│...
        ..a│...│d..
        ───┼───┼───
        .a.│A.D│...
        ...│...│...
        ...│C.B│.b.
        ───┼───┼───
        ..c│...│b..
        ...│c..│...
        ...│...│...
        """);
}
