<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Specs</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="App/Content.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Generator/Generator.csproj" />
    <ProjectReference Include="../Puzzles/Puzzles.csproj" />
    <ProjectReference Include="../Sudoku/Sudoku.csproj" />
    <ProjectReference Include="../Sudoku.App/Sudoku.App.csproj" />
  </ItemGroup>

  <ItemGroup Label="Solvers">
    <ProjectReference Include="../Dlx/Dlx.csproj" />
    <ProjectReference Include="../DynamicSolver/DynamicSolver.csproj" />
    <ProjectReference Include="../Reference/Reference.csproj" />
    <ProjectReference Include="../StrategyBased/StrategyBased.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup Label="Build Tools">
    <PackageReference PrivateAssets="all" Include="coverlet.collector" />
    <PackageReference PrivateAssets="all" Include="Microsoft.NET.Test.Sdk" />
    <PackageReference PrivateAssets="all" Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <PackageReference PrivateAssets="all" Include="AwesomeAssertions.Analyzers" />
    <PackageReference PrivateAssets="all" Include="NUnit.Analyzers" />
  </ItemGroup>
  
</Project>
