<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Specs</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Puzzles/Puzzles.csproj" />
    <ProjectReference Include="../SudokuSolver/SudokuSolver.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup Label="Build Tools">
    <PackageReference PrivateAssets="all" Include="coverlet.collector" />
    <PackageReference PrivateAssets="all" Include="Microsoft.NET.Test.Sdk" />
    <PackageReference PrivateAssets="all" Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup Label="Analyzers">
    <PackageReference PrivateAssets="all" Include="AwesomeAssertions.Analyzers" />
    <PackageReference PrivateAssets="all" Include="NUnit.Analyzers" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Update="DotNetProjectFile.Analyzers" Version="1.7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNetProjectFile.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
