namespace Puzzles.CrackingTheCryptic;

public sealed class _2021_05_01 : CtcPuzzle
{
    public override string Title => "Wave Particals";

    public override string? Author => "TotallyNormalCat";

    public override Uri? Url => new("https://youtu.be/XblUEEdC9k8");

    public override O Duration => O.ms10;

    public override Clues Clues { get; } = Clues.Parse("""
        ...│...│...
        5..│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        ───┼───┼───
        ...│...│...
        ...│...│...
        ...│...│...
        """);

    public override Cells Solution { get; } = Cells.Parse("""
        189│764│325
        536│892│174
        742│315│986
        ───┼───┼───
        397│651│248
        258│479│631
        614│238│759
        ───┼───┼───
        865│923│417
        473│186│592
        921│547│863
        """);

    public override Rules Constraints { get; } =
        Rules.Killer("""
        ...│...│...
        ...│...│.AA
        ...│...│...
        ───┼───┼───
        ...│...│...
        ..B│...│...
        ..B│...│...
        ───┼───┼───
        ...│CC.│...
        DD.│...│.EE
        ...│...│...
        A = 11  B = 12  C = 11  D = 11  E = 11
        """)
        + Arrows.Parse("""
        ...│...│...
        ...│.A.│...
        .DC│B..│...
        ───┼───┼───
        ...│...│...
        ...│.F.│...
        .IH│G..│...
        ───┼───┼───
        ...│...│...
        ...│.K.│...
        .NM│L..│...
        """)
        + Arrows.Parse("""
        ...│..B│CD.
        ...│.A.│...
        ...│...│...
        ───┼───┼───
        ...│..G│HI.
        ...│.F.│...
        ...│...│...
        ───┼───┼───
        ...│..L│MN.
        ...│.K.│...
        ...│...│...
        """);
}
