namespace Puzzles.CrackingTheCryptic;

public sealed class _2021_05_01 : CtcPuzzle
{
    public override string Title => "Wave Particals";

    public override string? Author => "TotallyNormalCat";

    public override Uri? Url => new("https://youtu.be/XblUEEdC9k8");

    public override O Duration => O.ms100;

    public override Cells Solution { get; } = Cells.New("""
        189│764│325
        536│892│174
        742│315│986
        ───┼───┼───
        397│651│248
        258│479│631
        614│238│759
        ───┼───┼───
        865│923│417
        473│186│592
        921│547│863
        """);

    protected override RuleSet GetConstraints() =>
        RuleSet.Killer("""
        ...│...│...
        5..│...│.AA
        ...│...│...
        ───┼───┼───
        ...│...│...
        ..B│...│...
        ..B│...│...
        ───┼───┼───
        ...│CC.│...
        DD.│...│.EE
        ...│...│...
        A = 11  B = 12  C = 11  D = 11  E = 11
        """)
        + Lines.Arrow("""
        ...│...│...
        ...│.A.│...
        .aa│a..│...
        ───┼───┼───
        ...│...│...
        ...│.B.│...
        .bb│b..│...
        ───┼───┼───
        ...│...│...
        ...│.C.│...
        .cc│c..│...
        """)
        + Lines.Arrow("""
        ...│..a│aa.
        ...│.A.│...
        ...│...│...
        ───┼───┼───
        ...│..b│bb.
        ...│.B.│...
        ...│...│...
        ───┼───┼───
        ...│..c│cc.
        ...│.C.│...
        ...│...│...
        """)
        + KillerCages.Extend;
}
