<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Generator/Generator.csproj" />
    <ProjectReference Include="../Puzzles/Puzzles.csproj" />
  </ItemGroup>

  <ItemGroup Label="Solvers">
    <ProjectReference Include="../Dlx/Dlx.csproj" />
    <ProjectReference Include="../DynamicSolver/DynamicSolver.csproj" />
    <ProjectReference Include="../Reference/Reference.csproj" />
    <ProjectReference Include="../StrategyBased/StrategyBased.csproj" />
    <ProjectReference Include="..\JvoSolver\JvoSolver.csproj" />
  </ItemGroup>

</Project>
