global using Sudoku.Contracts;
global using Sudoku.Diagnostics;
global using Sudoku.Generics;
global using Sudoku.Parsing;
global using Sudoku.Restrictions;
global using Sudoku.Sets;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Diagnostics.Contracts;
global using System.Linq;
global using System.Runtime.CompilerServices;
global using System.Text;
global using static Sudoku.Statics;
global using LookupDigits = Sudoku.Generics.DigitLookup<Sudoku.Digits>;
global using PosArray = System.Collections.Immutable.ImmutableArray<Sudoku.Pos>;
global using Rules = System.Collections.Generic.IEnumerable<Sudoku.Contracts.Rule>;
